In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
df = pd.read_csv("tz_electricity_consumption_100k.csv")

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [3]:
df.head()

,household_id,region,area_type,year,month,season,num_occupants,num_rooms,dwelling_type,income_band,monthly_income_tzs,connection_type,meter_type,tariff_category,connection_age_years,has_refrigerator,num_televisions,has_air_conditioner,num_fans,has_electric_water_heater,num_lighting_points,has_electric_cooker,num_smartphones_charged,has_washing_machine,avg_monthly_temp_c,monthly_consumption_kwh
0,TZ-HH-000001,Morogoro,Rural,2022,10,Cool Dry,3,4,Swahili House (Shared),Upper-Middle,2625000,Mini-grid,Prepaid (LUKU),T2 (General Usage),5,0,2,0,0,1,13,0,6,0,23.8,70.1
1,TZ-HH-000002,Arusha,Rural,2024,5,Long Rains,2,2,Swahili House (Shared),Low,149000,TANESCO Grid,Prepaid (LUKU),D1 (Lifeline),1,0,1,0,2,0,4,0,2,0,21.3,54.6
2,TZ-HH-000003,Zanzibar Urban/West,Urban,2024,11,Short Rains,6,4,Swahili House (Shared),Lower-Middle,837000,TANESCO Grid,Prepaid (LUKU),T1 (Domestic Low Usage),10,0,1,0,1,0,10,0,7,0,29.0,83.5
3,TZ-HH-000004,Tanga,Urban,2024,5,Long Rains,4,4,Single-Family House,Middle,950000,TANESCO Grid,Postpaid,T1 (Domestic Low Usage),3,0,2,0,4,1,9,0,3,0,28.3,179.8
4,TZ-HH-000005,Dar es Salaam,Urban,2023,5,Long Rains,3,4,Swahili House (Shared),High,4911000,TANESCO Grid,Prepaid (LUKU),T2 (General Usage),7,1,1,0,3,1,15,0,1,1,27.8,221.7

In [4]:
df.tail()

,household_id,region,area_type,year,month,season,num_occupants,num_rooms,dwelling_type,income_band,monthly_income_tzs,connection_type,meter_type,tariff_category,connection_age_years,has_refrigerator,num_televisions,has_air_conditioner,num_fans,has_electric_water_heater,num_lighting_points,has_electric_cooker,num_smartphones_charged,has_washing_machine,avg_monthly_temp_c,monthly_consumption_kwh
99995,TZ-HH-099996,Dar es Salaam,Urban,2022,1,Hot Dry,6,3,Single-Family House,Middle,783000,TANESCO Grid,Postpaid,T1 (Domestic Low Usage),3,0,0,0,1,0,10,0,4,0,29.0,51.9
99996,TZ-HH-099997,Mbeya,Rural,2023,12,Short Rains,5,4,Swahili House (Shared),Middle,839000,Mini-grid,Prepaid (LUKU),T1 (Domestic Low Usage),11,0,1,0,1,0,10,0,4,0,20.1,55.1
99997,TZ-HH-099998,Mbeya,Urban,2024,7,Cool Dry,5,4,Single-Family House,Upper-Middle,1645000,TANESCO Grid,Postpaid,T2 (General Usage),6,1,4,0,0,0,12,0,8,0,19.8,106.2
99998,TZ-HH-099999,Dar es Salaam,Urban,2024,1,Hot Dry,3,5,Bungalow,Upper-Middle,2426000,TANESCO Grid,Prepaid (LUKU),T2 (General Usage),10,1,1,0,2,1,14,0,3,0,31.7,148.6
99999,TZ-HH-100000,Kigoma,Urban,2023,4,Long Rains,7,5,Apartment,Middle,781000,TANESCO Grid,Prepaid (LUKU),T1 (Domestic Low Usage),11,1,2,0,1,0,11,0,5,0,25.5,153.0

In [5]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 100000
Columns : 26

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   household_id               100000 non-null  object
 1   region                     100000 non-null  object
 2   area_type                  100000 non-null  object
 3   year                       100000 non-null  int64
 4   month                      100000 non-null  int64
 5   season                     100000 non-null  object
 6   num_occupants              100000 non-null  int64
 7   num_rooms                  100000 non-null  int64
 8   dwelling_type              100000 non-null  object
 9   income_band                100000 non-null  object
 10  monthly_income_tzs         100000 non-null  int64
 11  connection_type            100000 non-null  object
 12  meter_type                 100000 non-null  object
 13  tariff_category            100000 non-null  object
 14  connection_age_years       100000 non-null  int64
 15  has_refrigerator           100000 non-null  int64
 16  num_televisions            100000 non-null  int64
 17  has_air_conditioner        100000 non-null  int64
 18  num_fans                   100000 non-null  int64
 19  has_electric_water_heater  100000 non-null  int64
 20  num_lighting_points        100000 non-null  int64
 21  has_electric_cooker        100000 non-null  int64
 22  num_smartphones_charged    100000 non-null  int64
 23  has_washing_machine        100000 non-null  int64
 24  avg_monthly_temp_c         100000 non-null  float64
 25  monthly_consumption_kwh    100000 non-null  float64
dtypes: float64(2), int64(15), object(9)
memory usage: 19.8+ MB

In [7]:
df.describe()

,year,month,num_occupants,num_rooms,monthly_income_tzs,connection_age_years,has_refrigerator,num_televisions,has_air_conditioner,num_fans,has_electric_water_heater,num_lighting_points,has_electric_cooker,num_smartphones_charged,has_washing_machine,avg_monthly_temp_c,monthly_consumption_kwh
count,100000.000000,100000.000000,100000.000000,100000.00000,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,2023.047380,6.510620,4.313150,3.42001,1.124106e+06,5.991570,0.295090,0.954100,0.069280,1.242110,0.090940,8.514660,0.046450,3.788220,0.085660,24.997056,82.096040
std,0.804153,3.457726,2.043303,1.29903,1.333938e+06,4.233301,0.456085,1.074609,0.253931,1.318996,0.287525,3.601488,0.210459,2.310143,0.279863,3.428396,70.087215
min,2022.000000,1.000000,1.000000,1.00000,9.600000e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,14.600000,4.000000
25%,2022.000000,3.000000,3.000000,3.00000,3.280000e+05,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,2.000000,0.000000,22.600000,37.600000
50%,2023.000000,7.000000,4.000000,3.00000,6.470000e+05,5.000000,0.000000,1.000000,0.000000,1.000000,0.000000,9.000000,0.000000,3.000000,0.000000,25.400000,63.100000
75%,2024.000000,10.000000,6.000000,4.00000,1.257000e+06,8.000000,1.000000,2.000000,0.000000,2.000000,0.000000,11.000000,0.000000,5.000000,0.000000,27.500000,105.900000
max,2024.000000,12.000000,12.000000,9.00000,1.459100e+07,30.000000,1.000000,4.000000,1.000000,6.000000,1.000000,23.000000,1.000000,12.000000,1.000000,34.300000,722.500000

In [8]:
df.describe(include='object')

,household_id,region,area_type,season,dwelling_type,income_band,connection_type,meter_type,tariff_category
count,100000,100000,100000,100000,100000,100000,100000,100000,100000
unique,100000,12,3,4,4,5,3,2,4
top,TZ-HH-000001,Dar es Salaam,Urban,Cool Dry,Swahili House (Shared),Lower-Middle,TANESCO Grid,Prepaid (LUKU),T1 (Domestic Low Usage)
freq,1,27995,48873,41856,68449,28599,79162,84759,47931

In [9]:
missing = df.isnull().sum()

missing = missing[missing > 0]

missing.sort_values(ascending=False)

Series([], dtype: int64)

In [10]:
missing_percent = (df.isnull().sum()/len(df))*100

missing_percent[missing_percent>0].sort_values(ascending=False)

Series([], dtype: float64)

In [11]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [12]:
df.dtypes

household_id                  object
region                        object
area_type                     object
year                           int64
month                          int64
season                        object
num_occupants                  int64
num_rooms                      int64
dwelling_type                 object
income_band                   object
monthly_income_tzs             int64
connection_type               object
meter_type                    object
tariff_category               object
connection_age_years           int64
has_refrigerator               int64
num_televisions                int64
has_air_conditioner            int64
num_fans                       int64
has_electric_water_heater      int64
num_lighting_points            int64
has_electric_cooker            int64
num_smartphones_charged        int64
has_washing_machine            int64
avg_monthly_temp_c           float64
monthly_consumption_kwh      float64
dtype: object

In [13]:
for col in df.columns:
    print(col)
    print(df[col].nunique())
    print("---------------------")

household_id
100000
---------------------
region
12
---------------------
area_type
3
---------------------
year
3
---------------------
month
12
---------------------
season
4
---------------------
num_occupants
12
---------------------
num_rooms
9
---------------------
dwelling_type
4
---------------------
income_band
5
---------------------
monthly_income_tzs
6690
---------------------
connection_type
3
---------------------
meter_type
2
---------------------
tariff_category
4
---------------------
connection_age_years
31
---------------------
has_refrigerator
2
---------------------
num_televisions
5
---------------------
has_air_conditioner
2
---------------------
num_fans
7
---------------------
has_electric_water_heater
2
---------------------
num_lighting_points
23
---------------------
has_electric_cooker
2
---------------------
num_smartphones_charged
13
---------------------
has_washing_machine
2
---------------------
avg_monthly_temp_c
190
---------------------
monthly_consumption_kwh
3973
---------------------

In [16]:
df.columns

Index(['household_id', 'region', 'area_type', 'year', 'month', 'season',
       'num_occupants', 'num_rooms', 'dwelling_type', 'income_band',
       'monthly_income_tzs', 'connection_type', 'meter_type',
       'tariff_category', 'connection_age_years', 'has_refrigerator',
       'num_televisions', 'has_air_conditioner', 'num_fans',
       'has_electric_water_heater', 'num_lighting_points',
       'has_electric_cooker', 'num_smartphones_charged', 'has_washing_machine',
       'avg_monthly_temp_c', 'monthly_consumption_kwh'],
      dtype='object')

In [18]:
target = "monthly_consumption_kwh"

X = df.drop(columns=[target, "household_id"])
y = df[target]

print("Features:", X.shape)
print("Target:", y.shape)

Features: (100000, 24)
Target: (100000,)

In [19]:
categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
numerical_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()

print("Categorical columns:", categorical_cols)
print("Numerical columns:", numerical_cols)

Categorical columns: ['region', 'area_type', 'season', 'dwelling_type', 'income_band', 'connection_type', 'meter_type', 'tariff_category']
Numerical columns: ['year', 'month', 'num_occupants', 'num_rooms', 'monthly_income_tzs', 'connection_age_years', 'has_refrigerator', 'num_televisions', 'has_air_conditioner', 'num_fans', 'has_electric_water_heater', 'num_lighting_points', 'has_electric_cooker', 'num_smartphones_charged', 'has_washing_machine', 'avg_monthly_temp_c']

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2, 
    random_state=42
)

print(X_train.shape, X_test.shape)

(80000, 24) (20000, 24)