In [1]:
# AI-Based Household Electricity Consumption Prediction

## 1. Import Libraries
## 2. Load Datasets
## 3. Understand Each Dataset
## 4. Identify Common Keys for Merging
## 5. Select Target Variable
## 6. Clean and Prepare Data
## 7. Exploratory Data Analysis
## 8. Feature Engineering
## 9. Model Training
## 10. Model Evaluation
## 11. Interpretation and Conclusion

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [3]:
demographic = pd.read_stata("sec_a_households_demographic.dta")
electricity = pd.read_stata("sec_2_electricity.dta")
cooking = pd.read_stata("sec_3_cooking.dta")
lighting = pd.read_stata("sec_6_lighting.dta")
quantities = pd.read_stata("sec_7_quantities_used.dta")

In [4]:
datasets = {
    "Demographic": demographic,
    "Electricity": electricity,
    "Cooking": cooking,
    "Lighting": lighting,
    "Quantities Used": quantities
}

In [5]:
for name, df in datasets.items():
    print(name)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("-" * 50)

Demographic
Rows: 58383
Columns: 40
--------------------------------------------------
Electricity
Rows: 12665
Columns: 41
--------------------------------------------------
Cooking
Rows: 12664
Columns: 66
--------------------------------------------------
Lighting
Rows: 12663
Columns: 61
--------------------------------------------------
Quantities Used
Rows: 12663
Columns: 99
--------------------------------------------------

In [6]:
for name, df in datasets.items():
    print(f"\n{name} Dataset")
    display(df.head())

Demographic Dataset

,hhid,reg_code,region,dist_code,dist_name,counc_code,counc_name,const_code,const_name,div_code,div_name,ward_code,ward_name,vill_code,vill_name,ea_code,hamlet,full_ea_code,hhnumber,rural_urban,seca_starttime,intervcode1,a1,r1__id,hhmember_Number,individualid,memberslist,hhsize,a6,a7,age_of_head,a9,a2,a3,age,a5,a6_1,a6_1_oth,interview__key,seca_interviewend
0,,,NaN,,,,,,,,,,,,,,,,,NaN,2024-08-08T20:05:28,CONFIDENTIAL,1,1,01,01,CONFIDENTIAL,1,1,Yes,23.0,1,Female,HEAD OF HOUSEHOLD,23,Never Married,Self employed (non farming): without employees,,01-96-70-35,2024-08-08T20:07:22
1,010111120210300901,01,Dodoma,01,Kondoa,11,Halmashauri ya Wilaya ya Kondoa,1,Kondoa,2,Kolo,021,Hondomairo,03,Mtiryangwi,009,Mtiryangwi,0101111202103009,01,Rural,2024-08-25T16:13:40,CONFIDENTIAL,4,1,01,01011112021030090101,CONFIDENTIAL,4,1,Yes,64.0,1,Female,HEAD OF HOUSEHOLD,64,Divorced,Crop Farming,,14-15-57-65,2024-08-25T16:18:12
2,010111120210300901,01,Dodoma,01,Kondoa,11,Halmashauri ya Wilaya ya Kondoa,1,Kondoa,2,Kolo,021,Hondomairo,03,Mtiryangwi,009,Mtiryangwi,0101111202103009,01,Rural,2024-08-25T16:13:40,CONFIDENTIAL,4,2,02,01011112021030090102,CONFIDENTIAL,4,1,Yes,64.0,2,Male,SON/DAUGHTER,28,Never Married,Crop Farming,,14-15-57-65,2024-08-25T16:18:12
3,010111120210300901,01,Dodoma,01,Kondoa,11,Halmashauri ya Wilaya ya Kondoa,1,Kondoa,2,Kolo,021,Hondomairo,03,Mtiryangwi,009,Mtiryangwi,0101111202103009,01,Rural,2024-08-25T16:13:40,CONFIDENTIAL,4,3,03,01011112021030090103,CONFIDENTIAL,4,1,Yes,64.0,1,Male,GRAND SON/DAUGHTER,11,Never Married,Unpaid family helper (non agriculture),,14-15-57-65,2024-08-25T16:18:12
4,010111120210300901,01,Dodoma,01,Kondoa,11,Halmashauri ya Wilaya ya Kondoa,1,Kondoa,2,Kolo,021,Hondomairo,03,Mtiryangwi,009,Mtiryangwi,0101111202103009,01,Rural,2024-08-25T16:13:40,CONFIDENTIAL,4,4,04,01011112021030090104,CONFIDENTIAL,4,1,Yes,64.0,1,Female,GRAND SON/DAUGHTER,4,NaN,NaN,,14-15-57-65,2024-08-25T16:18:12

Electricity Dataset

,hhid,region,rural_urban,interview__key,sec2_starttime,s2q2,s2q211,s2q212,s2q213,s2q214,s2q2141,s2q2141p,s2q21411,s2q21412,s2q2142,s2q21421,s2q21422,s2q2143,s2q21431,s2q21432,s2q2144,s2q21441,s2q21442,s2q21443,s2q2145,s2q215,s2q2151,s2q215a,s2q221,s2q222,s2q223,s2q224,s2q225,s2q226,s2q227,s2q2271,s2q228,s2q23,s2q24,s2q241,sec2_endtime
0,140311222310200104,Tabora,Rural,00-00-35-92,2024-08-08T16:49:38,YES,No,No,Yes,No,NaN,""" """,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,,No,,,NO,YES,NO,NO,YES,NO,NO,,,NaN,NaN,NaN,2024-08-08T16:50:57
1,020221221910300108,Arusha,Rural,00-00-44-09,2024-08-07T15:04:21,NO,NaN,NaN,NaN,NaN,NaN,""" """,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,2024-08-07T15:05:18
2,170123211420300709,Shinyanga,Urban,00-00-92-39,2024-08-18T14:02:44,YES,Yes,No,No,No,NaN,""" """,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,,No,,,NO,YES,NO,NO,YES,NO,NO,,,24.0,D1,9000.0,2024-08-18T14:06:10
3,250111120210300402,Geita,Rural,00-00-96-75,2024-08-08T16:34:36,NO,NaN,NaN,NaN,NaN,NaN,""" """,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,2024-08-08T16:34:50
4,220411131710700215,Njombe,Rural,00-00-99-67,2024-08-29T12:31:12,YES,Yes,No,No,No,NaN,""" """,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,,No,,,NO,YES,NO,NO,YES,NO,NO,,,28.0,T1,10000.0,2024-08-29T12:32:04

Cooking Dataset

,hhid,reg_code,region,dist_code,dist_name,counc_code,counc_name,const_code,const_name,div_code,div_name,ward_code,ward_name,vill_code,vill_name,ea_code,hamlet,full_ea_code,hhnumber,rural_urban,sec3_starttime,sec3_respondent,s3,s3q1,s3q2,s3q3,s3q31,s3q4,s3q41,s3q5,s3q51,s3q6,s3q61,s3q7,s3q71,s3q8,s3q81,s3q9,s3q91,s3q10,s3q101,s3q102,s3q103,s3q104,s3q104_qty,s3q11,s3q111,s3q112,s3q113,s3q114,s3q114_qty,s3q12,s3q121,s3q122,s3q123,s3q13,s3q131,s3q132,s3q133,s3q14,s3q141,s3q142,s3q143,s3q143a,sec3_endtime,interview__key
0,140311222310200104,14,Tabora,03,Uyui,11,Halmashauri ya Wilaya ya Uyui,2,Tabora Kaskazini,2,Uyui,231,Nsimbo,02,Nsimbo,001,Kiguhumo,1403112223102001,04,Rural,2024-08-08T16:51:00,2,NO,NaN,YES,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,YES,THREE-STONE STOVE,14.0,YES,1.3,1.3,NO,NaN,NaN,NaN,NaN,NaN,NO,,NaN,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,,2024-08-08T16:52:45,00-00-35-92
1,020221221910300108,02,Arusha,02,Arumeru,21,Halmashauri ya Wilaya ya Arusha,2,Arumeru Magharibi,2,Enaboishu,191,Sambasha,03,Shiboro,001,Masaga,0202212219103001,08,Rural,2024-08-07T15:05:21,2,NO,NaN,YES,NaN,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,YES,THREE-STONE STOVE,5.0,YES,2.0,2.0,NO,NaN,NaN,NaN,NaN,NaN,NO,,NaN,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,,2024-08-07T15:08:01,00-00-44-09
2,170123211420300709,17,Shinyanga,01,Kahama,23,Halmashauri ya Manispaa ya Kahama,2,Kahama Mjini,1,Kahama Mjini,142,Nyahanga,03,Nyahanga,007,Nyahanga-07,1701232114203007,09,Urban,2024-08-18T14:06:17,2,NO,NaN,NO,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NaN,NaN,NaN,NaN,YES,TRADITIONAL RAISED CHARCOAL STOVE,21.0,YES,3.4,1.5,NO,,NaN,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,,2024-08-18T14:08:43,00-00-92-39
3,250111120210300402,25,Geita,01,Geita,11,Halmashauri ya Wilaya ya Geita,1,Geita Vijijini,2,Bugando,021,Bugulula,03,Kasota,004,Senta,2501111202103004,02,Rural,2024-08-08T16:34:53,2,NO,NaN,NO,NaN,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,YES,THREE-STONE STOVE,14.0,NO,2.1,2.1,NO,NaN,NaN,NaN,NaN,NaN,NO,,NaN,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,,2024-08-08T16:39:08,00-00-96-75
4,220411131710700215,22,Njombe,04,Wanging'ombe,11,Halmashauri ya Wilaya ya Wanging'ombe,1,Wanging'ombe,3,Wanging'ombe,171,Luduga,07,Igando,002,Igando,2204111317107002,15,Rural,2024-08-29T12:32:09,1,NO,NaN,YES,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,NO,NaN,YES,ROUND MUD STOVE,21.0,YES,2.0,2.0,NO,NaN,NaN,NaN,NaN,NaN,NO,,NaN,NaN,NaN,,NaN,NaN,NaN,,NaN,NaN,,2024-08-29T12:33:26,00-00-99-67

Lighting Dataset

,hhid,reg_code,region,dist_code,dist_name,counc_code,counc_name,const_code,const_name,div_code,div_name,ward_code,ward_name,vill_code,vill_name,ea_code,hamlet,full_ea_code,hhnumber,rural_urban,sec6_starttime,s6q0,s6q1,s6q11,s6q12,s6q2,s6q21,s6q22,s6q3,s6q31,s6q32,s6q4,s6q41,s6q42,s6q5,s6q51,s6q52,s6q6,s6q61,s6q62,s6q7,s6q71,s6q72,s6q73,s6q73_qty,s6q8,s6q81,s6q82,s6q9,s6q91,s6q92,s6q10,s6q101,s6q102,s6q110,s6q111,s6q112,s6q113,s6q120,sec6_endtime,interview__key
0,140311222310200104,14,Tabora,03,Uyui,11,Halmashauri ya Wilaya ya Uyui,2,Tabora Kaskazini,2,Uyui,231,Nsimbo,02,Nsimbo,001,Kiguhumo,1403112223102001,04,Rural,2024-08-08T16:53:50,YES,YES,3.0,5.0,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,1.0,YES,3.0,4.0,NO,NaN,NaN,NO,NaN,NaN,NO,,NaN,NaN,,2024-08-08T16:54:58,00-00-35-92
1,020221221910300108,02,Arusha,02,Arumeru,21,Halmashauri ya Wilaya ya Arusha,2,Arumeru Magharibi,2,Enaboishu,191,Sambasha,03,Shiboro,001,Masaga,0202212219103001,08,Rural,2024-08-07T15:09:11,YES,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NaN,1.0,NO,NaN,NaN,YES,18.0,3.0,NO,NaN,NaN,NO,,NaN,NaN,,2024-08-07T15:12:08,00-00-44-09
2,170123211420300709,17,Shinyanga,01,Kahama,23,Halmashauri ya Manispaa ya Kahama,2,Kahama Mjini,1,Kahama Mjini,142,Nyahanga,03,Nyahanga,007,Nyahanga-07,1701232114203007,09,Urban,2024-08-18T14:10:27,YES,YES,3.0,5.0,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,1.0,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,,NaN,NaN,,2024-08-18T14:11:26,00-00-92-39
3,250111120210300402,25,Geita,01,Geita,11,Halmashauri ya Wilaya ya Geita,1,Geita Vijijini,2,Bugando,021,Bugulula,03,Kasota,004,Senta,2501111202103004,02,Rural,2024-08-08T16:36:36,YES,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NaN,1.0,NO,NaN,NaN,YES,24.0,4.0,NO,NaN,NaN,NO,,NaN,NaN,,2024-08-08T16:37:39,00-00-96-75
4,220411131710700215,22,Njombe,04,Wanging'ombe,11,Halmashauri ya Wilaya ya Wanging'ombe,1,Wanging'ombe,3,Wanging'ombe,171,Luduga,07,Igando,002,Igando,2204111317107002,15,Rural,2024-08-29T12:34:21,YES,YES,4.0,4.0,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,1.0,NO,NaN,NaN,NO,NaN,NaN,NO,NaN,NaN,NO,,NaN,NaN,,2024-08-29T12:35:16,00-00-99-67

Quantities Used Dataset

,hhid,reg_code,region,dist_code,dist_name,counc_code,counc_name,const_code,const_name,div_code,div_name,ward_code,ward_name,vill_code,vill_name,ea_code,hamlet,full_ea_code,hhnumber,rural_urban,sec7_starttime,s7q11,s7q11a,s7q12a,s7q12b,s7q13,lpgprice,s7q21,s7q21a,s7q22a,s7q23,keroseneprice,s7q31,s7q31a,s7q32a,s7q33,s7q41,s7q41a,s7q42a,s7q43,s7q51,s7q51a,s7q52,s7q53,s7q61,s7q61a,s7q62,s7q71,s7q72,s7q72a,s7q73,s7q8,s7q81,s7q81a,s7q82,s7q83,s7q84,s7q9,s7q91,s7q91a,s7q92,charcoal_price_bucket,s7q10,s7q101,s7q101a,s7q101aa,s7q102,s7q11_1,s7q111,s7q111a,s7q111aa,s7q112,s7q12_1,s7q121,s7q121a,s7q121aa,s7q122,s7q131,s7q132,s7q132a,s7q132aa,s7q133,s7q141,s7q142,s7q142a,s7q142aa,s7q143,s7q151,s7q152,s7q152a,s7q152aa,s7q153,s7q161,s7q162,s7q162a,s7q162aa,s7q163,sec7_endtime,interview__key
0,140311222310200104,14,Tabora,03,Uyui,11,Halmashauri ya Wilaya ya Uyui,2,Tabora Kaskazini,2,Uyui,231,Nsimbo,02,Nsimbo,001,Kiguhumo,1403112223102001,04,Rural,2024-08-08T16:55:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-08T16:55:55,00-00-35-92
1,020221221910300108,02,Arusha,02,Arumeru,21,Halmashauri ya Wilaya ya Arusha,2,Arumeru Magharibi,2,Enaboishu,191,Sambasha,03,Shiboro,001,Masaga,0202212219103001,08,Rural,2024-08-07T15:12:13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YES,6.0,Monthly,12000.0,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-07T15:13:05,00-00-44-09
2,170123211420300709,17,Shinyanga,01,Kahama,23,Halmashauri ya Manispaa ya Kahama,2,Kahama Mjini,1,Kahama Mjini,142,Nyahanga,03,Nyahanga,007,Nyahanga-07,1701232114203007,09,Urban,2024-08-18T14:11:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YES,1.0,Monthly,9439.0,30000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-18T14:13:01,00-00-92-39
3,250111120210300402,25,Geita,01,Geita,11,Halmashauri ya Wilaya ya Geita,1,Geita Vijijini,2,Bugando,021,Bugulula,03,Kasota,004,Senta,2501111202103004,02,Rural,2024-08-08T16:37:44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,NaN,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-08T16:38:04,00-00-96-75
4,220411131710700215,22,Njombe,04,Wanging'ombe,11,Halmashauri ya Wilaya ya Wanging'ombe,1,Wanging'ombe,3,Wanging'ombe,171,Luduga,07,Igando,002,Igando,2204111317107002,15,Rural,2024-08-29T12:35:22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YES,15.0,Monthly,30000.0,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-08-29T12:39:14,00-00-99-67

In [7]:
for name, df in datasets.items():
    print(f"\n{name} Columns")
    print(df.columns.tolist())

Demographic Columns
['hhid', 'reg_code', 'region', 'dist_code', 'dist_name', 'counc_code', 'counc_name', 'const_code', 'const_name', 'div_code', 'div_name', 'ward_code', 'ward_name', 'vill_code', 'vill_name', 'ea_code', 'hamlet', 'full_ea_code', 'hhnumber', 'rural_urban', 'seca_starttime', 'intervcode1', 'a1', 'r1__id', 'hhmember_Number', 'individualid', 'memberslist', 'hhsize', 'a6', 'a7', 'age_of_head', 'a9', 'a2', 'a3', 'age', 'a5', 'a6_1', 'a6_1_oth', 'interview__key', 'seca_interviewend']

Electricity Columns
['hhid', 'region', 'rural_urban', 'interview__key', 'sec2_starttime', 's2q2', 's2q211', 's2q212', 's2q213', 's2q214', 's2q2141', 's2q2141p', 's2q21411', 's2q21412', 's2q2142', 's2q21421', 's2q21422', 's2q2143', 's2q21431', 's2q21432', 's2q2144', 's2q21441', 's2q21442', 's2q21443', 's2q2145', 's2q215', 's2q2151', 's2q215a', 's2q221', 's2q222', 's2q223', 's2q224', 's2q225', 's2q226', 's2q227', 's2q2271', 's2q228', 's2q23', 's2q24', 's2q241', 'sec2_endtime']

Cooking Columns
['hhid', 'reg_code', 'region', 'dist_code', 'dist_name', 'counc_code', 'counc_name', 'const_code', 'const_name', 'div_code', 'div_name', 'ward_code', 'ward_name', 'vill_code', 'vill_name', 'ea_code', 'hamlet', 'full_ea_code', 'hhnumber', 'rural_urban', 'sec3_starttime', 'sec3_respondent', 's3', 's3q1', 's3q2', 's3q3', 's3q31', 's3q4', 's3q41', 's3q5', 's3q51', 's3q6', 's3q61', 's3q7', 's3q71', 's3q8', 's3q81', 's3q9', 's3q91', 's3q10', 's3q101', 's3q102', 's3q103', 's3q104', 's3q104_qty', 's3q11', 's3q111', 's3q112', 's3q113', 's3q114', 's3q114_qty', 's3q12', 's3q121', 's3q122', 's3q123', 's3q13', 's3q131', 's3q132', 's3q133', 's3q14', 's3q141', 's3q142', 's3q143', 's3q143a', 'sec3_endtime', 'interview__key']

Lighting Columns
['hhid', 'reg_code', 'region', 'dist_code', 'dist_name', 'counc_code', 'counc_name', 'const_code', 'const_name', 'div_code', 'div_name', 'ward_code', 'ward_name', 'vill_code', 'vill_name', 'ea_code', 'hamlet', 'full_ea_code', 'hhnumber', 'rural_urban', 'sec6_starttime', 's6q0', 's6q1', 's6q11', 's6q12', 's6q2', 's6q21', 's6q22', 's6q3', 's6q31', 's6q32', 's6q4', 's6q41', 's6q42', 's6q5', 's6q51', 's6q52', 's6q6', 's6q61', 's6q62', 's6q7', 's6q71', 's6q72', 's6q73', 's6q73_qty', 's6q8', 's6q81', 's6q82', 's6q9', 's6q91', 's6q92', 's6q10', 's6q101', 's6q102', 's6q110', 's6q111', 's6q112', 's6q113', 's6q120', 'sec6_endtime', 'interview__key']

Quantities Used Columns
['hhid', 'reg_code', 'region', 'dist_code', 'dist_name', 'counc_code', 'counc_name', 'const_code', 'const_name', 'div_code', 'div_name', 'ward_code', 'ward_name', 'vill_code', 'vill_name', 'ea_code', 'hamlet', 'full_ea_code', 'hhnumber', 'rural_urban', 'sec7_starttime', 's7q11', 's7q11a', 's7q12a', 's7q12b', 's7q13', 'lpgprice', 's7q21', 's7q21a', 's7q22a', 's7q23', 'keroseneprice', 's7q31', 's7q31a', 's7q32a', 's7q33', 's7q41', 's7q41a', 's7q42a', 's7q43', 's7q51', 's7q51a', 's7q52', 's7q53', 's7q61', 's7q61a', 's7q62', 's7q71', 's7q72', 's7q72a', 's7q73', 's7q8', 's7q81', 's7q81a', 's7q82', 's7q83', 's7q84', 's7q9', 's7q91', 's7q91a', 's7q92', 'charcoal_price_bucket', 's7q10', 's7q101', 's7q101a', 's7q101aa', 's7q102', 's7q11_1', 's7q111', 's7q111a', 's7q111aa', 's7q112', 's7q12_1', 's7q121', 's7q121a', 's7q121aa', 's7q122', 's7q131', 's7q132', 's7q132a', 's7q132aa', 's7q133', 's7q141', 's7q142', 's7q142a', 's7q142aa', 's7q143', 's7q151', 's7q152', 's7q152a', 's7q152aa', 's7q153', 's7q161', 's7q162', 's7q162a', 's7q162aa', 's7q163', 'sec7_endtime', 'interview__key']

In [8]:
electricity.columns.tolist()
quantities.columns.tolist()

['hhid',
 'reg_code',
 'region',
 'dist_code',
 'dist_name',
 'counc_code',
 'counc_name',
 'const_code',
 'const_name',
 'div_code',
 'div_name',
 'ward_code',
 'ward_name',
 'vill_code',
 'vill_name',
 'ea_code',
 'hamlet',
 'full_ea_code',
 'hhnumber',
 'rural_urban',
 'sec7_starttime',
 's7q11',
 's7q11a',
 's7q12a',
 's7q12b',
 's7q13',
 'lpgprice',
 's7q21',
 's7q21a',
 's7q22a',
 's7q23',
 'keroseneprice',
 's7q31',
 's7q31a',
 's7q32a',
 's7q33',
 's7q41',
 's7q41a',
 's7q42a',
 's7q43',
 's7q51',
 's7q51a',
 's7q52',
 's7q53',
 's7q61',
 's7q61a',
 's7q62',
 's7q71',
 's7q72',
 's7q72a',
 's7q73',
 's7q8',
 's7q81',
 's7q81a',
 's7q82',
 's7q83',
 's7q84',
 's7q9',
 's7q91',
 's7q91a',
 's7q92',
 'charcoal_price_bucket',
 's7q10',
 's7q101',
 's7q101a',
 's7q101aa',
 's7q102',
 's7q11_1',
 's7q111',
 's7q111a',
 's7q111aa',
 's7q112',
 's7q12_1',
 's7q121',
 's7q121a',
 's7q121aa',
 's7q122',
 's7q131',
 's7q132',
 's7q132a',
 's7q132aa',
 's7q133',
 's7q141',
 's7q142',
 's7q142a',
 's7q142aa',
 's7q143',
 's7q151',
 's7q152',
 's7q152a',
 's7q152aa',
 's7q153',
 's7q161',
 's7q162',
 's7q162a',
 's7q162aa',
 's7q163',
 'sec7_endtime',
 'interview__key']

In [9]:
for name1, df1 in datasets.items():
    for name2, df2 in datasets.items():
        if name1 != name2:
            common_cols = set(df1.columns).intersection(set(df2.columns))
            print(f"\nCommon columns between {name1} and {name2}:")
            print(common_cols)

Common columns between Demographic and Electricity:
{'rural_urban', 'hhid', 'region', 'interview__key'}

Common columns between Demographic and Cooking:
{'dist_name', 'full_ea_code', 'hhnumber', 'hhid', 'hamlet', 'interview__key', 'counc_code', 'ward_code', 'counc_name', 'region', 'rural_urban', 'dist_code', 'div_name', 'reg_code', 'ea_code', 'ward_name', 'const_name', 'const_code', 'vill_name', 'div_code', 'vill_code'}

Common columns between Demographic and Lighting:
{'dist_name', 'full_ea_code', 'hhnumber', 'hhid', 'hamlet', 'interview__key', 'counc_code', 'ward_code', 'counc_name', 'region', 'rural_urban', 'dist_code', 'div_name', 'reg_code', 'ea_code', 'ward_name', 'const_name', 'const_code', 'vill_name', 'div_code', 'vill_code'}

Common columns between Demographic and Quantities Used:
{'dist_name', 'full_ea_code', 'hhnumber', 'hhid', 'hamlet', 'interview__key', 'counc_code', 'ward_code', 'counc_name', 'region', 'rural_urban', 'dist_code', 'div_name', 'reg_code', 'ea_code', 'ward_name', 'const_name', 'const_code', 'vill_name', 'div_code', 'vill_code'}

Common columns between Electricity and Demographic:
{'rural_urban', 'hhid', 'region', 'interview__key'}

Common columns between Electricity and Cooking:
{'rural_urban', 'hhid', 'region', 'interview__key'}

Common columns between Electricity and Lighting:
{'rural_urban', 'hhid', 'region', 'interview__key'}

Common columns between Electricity and Quantities Used:
{'rural_urban', 'hhid', 'region', 'interview__key'}

Common columns between Cooking and Demographic:
{'dist_name', 'full_ea_code', 'hhnumber', 'hhid', 'hamlet', 'interview__key', 'counc_code', 'ward_code', 'counc_name', 'region', 'rural_urban', 'dist_code', 'div_name', 'reg_code', 'ea_code', 'ward_name', 'const_name', 'const_code', 'vill_name', 'div_code', 'vill_code'}

Common columns between Cooking and Electricity:
{'rural_urban', 'hhid', 'region', 'interview__key'}

Common columns between Cooking and Lighting:
{'dist_name', 'full_ea_code', 'hhnumber', 'hhid', 'hamlet', 'interview__key', 'counc_code', 'ward_code', 'counc_name', 'region', 'rural_urban', 'dist_code', 'div_name', 'reg_code', 'ea_code', 'ward_name', 'const_name', 'const_code', 'vill_name', 'div_code', 'vill_code'}

Common columns between Cooking and Quantities Used:
{'dist_name', 'full_ea_code', 'hhnumber', 'hhid', 'hamlet', 'interview__key', 'counc_code', 'ward_code', 'counc_name', 'region', 'rural_urban', 'dist_code', 'div_name', 'reg_code', 'ea_code', 'ward_name', 'const_name', 'const_code', 'vill_name', 'div_code', 'vill_code'}

Common columns between Lighting and Demographic:
{'dist_name', 'full_ea_code', 'hhnumber', 'hhid', 'hamlet', 'interview__key', 'counc_code', 'ward_code', 'counc_name', 'region', 'rural_urban', 'dist_code', 'div_name', 'reg_code', 'ea_code', 'ward_name', 'const_name', 'const_code', 'vill_name', 'div_code', 'vill_code'}

Common columns between Lighting and Electricity:
{'rural_urban', 'hhid', 'region', 'interview__key'}

Common columns between Lighting and Cooking:
{'dist_name', 'full_ea_code', 'hhnumber', 'hhid', 'hamlet', 'interview__key', 'counc_code', 'ward_code', 'counc_name', 'region', 'rural_urban', 'dist_code', 'div_name', 'reg_code', 'ea_code', 'ward_name', 'const_name', 'const_code', 'vill_name', 'div_code', 'vill_code'}

Common columns between Lighting and Quantities Used:
{'dist_name', 'full_ea_code', 'hhnumber', 'hhid', 'hamlet', 'interview__key', 'counc_code', 'ward_code', 'counc_name', 'region', 'rural_urban', 'dist_code', 'div_name', 'reg_code', 'ea_code', 'ward_name', 'const_name', 'const_code', 'vill_name', 'div_code', 'vill_code'}

Common columns between Quantities Used and Demographic:
{'dist_name', 'full_ea_code', 'hhnumber', 'hhid', 'hamlet', 'interview__key', 'counc_code', 'ward_code', 'counc_name', 'region', 'rural_urban', 'dist_code', 'div_name', 'reg_code', 'ea_code', 'ward_name', 'const_name', 'const_code', 'vill_name', 'div_code', 'vill_code'}

Common columns between Quantities Used and Electricity:
{'rural_urban', 'hhid', 'region', 'interview__key'}

Common columns between Quantities Used and Cooking:
{'dist_name', 'full_ea_code', 'hhnumber', 'hhid', 'hamlet', 'interview__key', 'counc_code', 'ward_code', 'counc_name', 'region', 'rural_urban', 'dist_code', 'div_name', 'reg_code', 'ea_code', 'ward_name', 'const_name', 'const_code', 'vill_name', 'div_code', 'vill_code'}

Common columns between Quantities Used and Lighting:
{'dist_name', 'full_ea_code', 'hhnumber', 'hhid', 'hamlet', 'interview__key', 'counc_code', 'ward_code', 'counc_name', 'region', 'rural_urban', 'dist_code', 'div_name', 'reg_code', 'ea_code', 'ward_name', 'const_name', 'const_code', 'vill_name', 'div_code', 'vill_code'}